# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='plannedEndDate',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='plannedPrice',
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
