# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170314_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='published',
            old_name='avrPrice',
            new_name='price',
        ),
    ]
