# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-25 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170320_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Employee'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='signDate',
            field=models.DateField(null=True),
        ),
    ]
